import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PROJECTS, projectSlug } from "@/data/projects";

const tones = { warm: "linear-gradient(150deg,#2c1a0d,#4a2f17 45%,#0a0707)", shadow: "linear-gradient(160deg,#14110f,#241d18 50%,#0b0908)", atelier: "linear-gradient(135deg,#1a1611,#34291b 45%,#0a0807)" };

export function generateStaticParams() { return PROJECTS.map((project) => ({ slug: projectSlug(project) })); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata> { const {slug}=await params; const p=PROJECTS.find((item)=>projectSlug(item)===slug); return p ? {title:p.title,description:p.overview??p.brief,alternates:{canonical:`/work/${slug}`}} : {}; }

export default async function ProjectPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const project=PROJECTS.find((item)=>projectSlug(item)===slug); if(!project) notFound();
  const schema={"@context":"https://schema.org","@type":"CreativeWork",name:project.title,dateCreated:project.year,description:project.overview,image:project.image?`/work/${slug}/cover.jpg`:undefined,creator:{"@type":"Organization",name:"Ruined"}};
  return <main className="min-h-screen bg-[#0b0908] px-6 pb-28 pt-28 text-[var(--color-bone)] sm:px-10 sm:pt-36"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><div className="mx-auto max-w-6xl"><div className="flex justify-between font-mono text-[0.58rem] uppercase tracking-[0.3em] text-white/45"><Link href="/work#record-index">← Project index</Link><span>Nº {project.no} · {project.year}</span></div><div className="mt-10 grid gap-10 md:grid-cols-12 md:gap-16"><div className="relative aspect-square overflow-hidden md:col-span-6" style={{background:tones[project.tone]}}>{project.image&&<Image src={project.image} alt={project.title} fill priority sizes="(min-width: 768px) 50vw, 100vw" className="object-cover"/>}<span className="absolute bottom-5 left-5 font-mono text-xs uppercase tracking-[0.3em] text-white/55">RU / {project.no}</span></div><article className="md:col-span-6 md:pt-8"><p className="font-mono text-[0.6rem] uppercase tracking-[0.3em] text-[var(--color-verdigris)]">{project.medium} · {project.status}</p><h1 className="display mt-4 text-[clamp(3rem,8vw,6rem)] leading-[0.88]">{project.title}</h1><p className="mt-5 text-lg text-white/55">{project.brief}</p><p className="mt-8 max-w-prose text-base leading-relaxed text-white/75">{project.overview}</p><dl className="mt-9 grid gap-5 border-y border-white/15 py-7 font-mono text-[0.58rem] uppercase tracking-[0.2em] sm:grid-cols-2"><div><dt className="text-white/35">Edition</dt><dd className="mt-1">{project.edition}</dd></div><div><dt className="text-white/35">Status</dt><dd className="mt-1">{project.status}</dd></div><div className="sm:col-span-2"><dt className="text-white/35">Materials</dt><dd className="mt-1 leading-relaxed">{project.materials?.join(" · ")}</dd></div></dl><div className="mt-9 flex gap-5 font-mono text-[0.58rem] uppercase tracking-[0.25em]"><Link className="underline underline-offset-8" href="/work">All projects</Link><Link className="underline underline-offset-8" href="/contact">Discuss a project</Link></div></article></div></div></main>;
}
