import type { MembershipLandingMode } from "./MembershipOfferSection";
import styles from "./MembershipOverview.module.css";

export default function MembershipQuestions({ mode, registrationOnly = false }: { mode: MembershipLandingMode; registrationOnly?: boolean }) {
  const registrationOpen = registrationOnly && mode !== "waitlist";
  const groups = [
    { title: "Getting started", items: [
      ["What happens after I register?", registrationOpen ? "Create your invitation, confirm your email with a code, fill out your information, and save your card securely. No payment is taken. We’ll send a welcome email once registration is complete. Your profile stays closed until a separate activation email arrives; signing in before then shows your registration status." : mode === "waitlist" ? "You join the waitlist. We’ll email you when it’s time to take the next step. Joining the waitlist does not start a paid membership or reserve a founding rate." : mode === "payment-setup" ? "Enter your name and email to create your personalized invitation here. We’ll send a confirmation code to your email. Enter it here to verify your address, accept your invitation, and continue to your profile. You can optionally save a payment method. Foundations remains closed until launch; preparing your profile does not activate paid membership." : "Enter your name and email to create your personalized invitation here. We’ll send a confirmation code to your email. Enter it here to verify your address, accept your invitation, and continue to your profile. Review your available offer and membership agreement, then confirm payment to activate paid membership. Foundations and other experiences become available as they launch."],
      ["When do I begin Foundations?", registrationOpen ? "Registration comes first. We’ll email you when your profile opens, then share the next steps for Foundations as it launches. Saving a card does not unlock your profile, Foundations, calls, or Circles early." : mode === "paid" ? "After you have completed member entry and your membership is active, you can begin when Foundations is available. Your member home shows the next step; upcoming facilitated sessions are published in Events." : "Foundations is being prepared for launch. Your member home will show when it is available. Registering or saving a payment method does not unlock it early. We’ll share start instructions when it is ready."],
      ["Is Foundations one-time or ongoing?", "Foundations is a one-time starting point for every member: four live virtual sessions over one month, 90 minutes each. You complete it once before moving into the ongoing monthly work. Complete the required personal work, including your Timeline and Future Letter. Your Circle is arranged during Foundations and revealed when you complete it."],
      ["Someone already invited me. What should I do?", "Open their invitation link and use the email it was sent to. That keeps your membership connected to the person who invited you."],
    ] },
    { title: "Calls & personal work", items: [
      ["When are the calls, and how do I join?", "Dates, times, and joining details appear in member Events as sessions are scheduled. Check the time zone shown on each event."],
      ["What if I miss a call? Are there recordings?", "Check the individual session details for replay availability. A replay is not promised for every conversation, and you should not record other members without permission. If you need a membership you can complete entirely through recordings, talk with us before joining."],
      ["How much time should I set aside?", "The four 90-minute membership calls total six hours each month. Add two Circle meetings and time to try the work between conversations. Foundations is a separate, one-time series of four live virtual sessions over one month, 90 minutes each. Circle meeting lengths and dates are shared with the group."],
      ["Is this therapy? Do I need to have experienced a crisis?", "Ruined is a personal-development community, not clinical mental-health care. You do not need a crisis or dramatic backstory to join. You may be rebuilding, rethinking what matters, or simply ready to make an intentional change."],
    ] },
    { title: "Your Circle & community", items: [
      ["How is my Circle chosen? Can I change it?", "The placement team considers your time zone, availability, known connections, and available places. Circles bring together 8–12 members, including a Supporter. They’re built for continuity and may evolve or divide as the community grows. Couples who register together on a shared membership are placed in the same Circle. Otherwise, a specific group is not guaranteed. If the fit or schedule needs attention, contact the team to discuss a move."],
      ["Can couples join together?", "Yes. Couples membership covers two named adults with separate accounts on one bill. Each person completes their own profile and agreement and approves the shared membership arrangement. You will be placed in the same Circle, and any Circle move keeps you together."],
      ["What does a Circle Supporter do?", "Your Circle Supporter helps guide the conversation and keep the group connected. The WHY meeting explores what is underneath the monthly topic. The IMPLEMENTATION meeting returns to what you tried and what you will do next. Everyone contributes to the conversation and follow-through."],
      ["What should stay private?", "Respect the personal stories people share. Keep nonpublic Circle conversations and other members’ private information within the group. Review your own sharing choices before publishing profile or entry content. The examples on this page are illustrative, not private member submissions."],
      ["Are events, apparel, and other items included?", "Not every event or physical item is included. Each experience lists its availability, access conditions, and any separate price. Apparel and artifacts are offered separately unless a specific offer says otherwise."],
    ] },
    { title: "Payment & membership", items: [
      ["When do I pay?", registrationOpen ? "Nothing is charged during registration. Saving a card is required to complete standard registration, but does not authorize a future charge. Opening your profile also does not start billing. You’ll review the available offer, agreement, and payment terms and explicitly confirm payment before paid membership begins." : mode === "paid" ? "Your first monthly installment or full annual payment is due when you activate paid membership. Applicable tax is shown before you authorize payment. Foundations is included; monthly and annual plans provide the same membership benefits." : "There is no payment due to join the waitlist or prepare your profile. If card saving is available, it is optional and does not authorize future charges. When paid membership opens, you review the current offer, agreement, and payment terms, then explicitly confirm payment."],
      ["Can I cancel?", "Paid membership starts with a 12-month commitment. You can turn off renewal, but doing so does not erase the initial monthly installments. Early exit from the initial monthly commitment costs the lower of $1,500 or the remaining unpaid installments, replacing those installments. After the initial term, monthly membership continues month to month until canceled. Prepaid annual plans renew annually unless renewal is turned off. Refund requests are reviewed individually, with applicable rights preserved."],
      ["What happens to founding pricing if I leave?", "The awarded founding rate remains while your membership stays continuously active, even as the community grows. When your membership ends, founding benefits end. If you rejoin, eligibility is checked again against the current active registered membership. Your old member number does not automatically restore the rate."],
      ["Who can join?", "Membership is for adults 18 and over in the United States. People of different backgrounds and stages of life are welcome. What matters here is your willingness to participate, listen, and contribute."],
    ] },
  ];
  return <section className={`${styles.wrap} ${styles.faq}`} id="membership-questions" aria-labelledby="questions-heading">
    <div><p className={styles.eyebrow}>The finer details</p><h2 id="questions-heading">Questions.</h2><a className={styles.textLink} href="mailto:connect@theruinedproject.com">Talk to us <span aria-hidden="true">↗</span></a></div>
    <div className={styles.questions}>{groups.map(group => <details key={group.title} className={styles.questionGroup}>
      <summary className={styles.questionCategory}><span>{group.title}<small>{group.items.length} questions</small></span><span aria-hidden="true">+</span></summary>
      <div className={styles.categoryAnswers}>{group.items.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div>
    </details>)}</div>
  </section>;
}
