import type {
  OpsAcademyEditorData,
  OpsAcademySnapshot,
} from "@/lib/platform/ops-academy-model";

export const PREVIEW_OPS_ACADEMY: OpsAcademySnapshot = {
  canManage: true,
  collections: [
    {
      collectionId: "preview-foundations",
      name: "Foundations",
      position: 1,
      publishedAt: "2026-08-20T18:00:00.000Z",
      resourceCount: 2,
      revision: 3,
      slug: "foundations",
      status: "published",
      summary: "The practices that hold the work together.",
    },
    {
      collectionId: "preview-making",
      name: "Making",
      position: 2,
      publishedAt: null,
      resourceCount: 1,
      revision: 1,
      slug: "making",
      status: "draft",
      summary: "Material, restraint, and repeatable craft.",
    },
  ],
  counts: { draft: 1, published: 2, retired: 0, unpublished: 0 },
  resources: [
    {
      audiences: [{ id: null, kind: "all_members", label: "All active members" }],
      collectionId: "preview-foundations",
      collectionName: "Foundations",
      contentType: "video",
      currentVersion: 2,
      hasUnpublishedChanges: false,
      latestVersion: 2,
      position: 1,
      publishedAt: "2026-08-20T18:00:00.000Z",
      resourceId: "preview-welcome",
      revision: 4,
      slug: "welcome-to-ruined",
      status: "published",
      summary: "A short orientation to the work and the people beside you.",
      thumbnailUrl: "/membership/academy/welcome-to-ruined.webp",
      title: "Welcome to Ruined",
    },
    {
      audiences: [{ id: "preview-circle-01", kind: "circle", label: "Circle 01" }],
      collectionId: "preview-foundations",
      collectionName: "Foundations",
      contentType: "article",
      currentVersion: 1,
      hasUnpublishedChanges: true,
      latestVersion: 2,
      position: 2,
      publishedAt: "2026-08-22T18:00:00.000Z",
      resourceId: "preview-circle-practice",
      revision: 3,
      slug: "the-circle-practice",
      status: "published",
      summary: "A working draft is waiting behind the live lesson.",
      thumbnailUrl: null,
      title: "The Circle Practice",
    },
    {
      audiences: [],
      collectionId: "preview-making",
      collectionName: "Making",
      contentType: "video",
      currentVersion: null,
      hasUnpublishedChanges: true,
      latestVersion: 1,
      position: 1,
      publishedAt: null,
      resourceId: "preview-material",
      revision: 1,
      slug: "material-before-decoration",
      status: "draft",
      summary: "A draft lesson awaiting its audience and final media.",
      thumbnailUrl: null,
      title: "Material Before Decoration",
    },
  ],
};

export const PREVIEW_OPS_ACADEMY_EDITOR: OpsAcademyEditorData = {
  canManage: true,
  options: {
    blocks: [{ id: "preview-block-01", label: "Block 01" }],
    circles: [{ id: "preview-circle-01", label: "Circle 01" }],
    collections: PREVIEW_OPS_ACADEMY.collections.map((collection) => ({
      id: collection.collectionId,
      label: collection.name,
      status: collection.status,
    })),
  },
  resource: {
    ...PREVIEW_OPS_ACADEMY.resources[0],
    bodyText: "Begin with what is true. Remove what only performs certainty.",
    captionsUrl: "https://example.com/welcome.vtt",
    durationLabel: "08:14",
    externalUrl: "https://example.com/welcome.mp4",
    featured: true,
    presenter: "Cade Mangelson",
    videoUrl: "https://example.com/welcome.mp4",
  },
};
